overrides:
  '@types/react': 19.2.17
  '@types/react-dom': 19.2.3
  nanoid: 3.3.18
  ws: 8.21.0
publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
allowBuilds:
  core-js: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@posthog/core@1.48.3'
  - '@posthog/types@1.405.0'
  - posthog-js@1.418.1
