import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";

import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { Footer } from "./components/Footer";

export const metadata: Metadata = {
  title: "Jason Huang",
  description: "Generated by create next app",
  verification: {
    google: "dTPtm5dSnc1vpyvOWE7Y21OhVMZW7gMFOC8gGRAGTlc",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <ReactQueryDevtools />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
