import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import Providers from "./providers";

import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { Footer } from "./components/Footer";

export const metadata: Metadata = {
  title: "Jason Huang",
  description: "Generated by create next app",
  verification: {
    google: "dTPtm5dSnc1vpyvOWE7Y21OhVMZW7gMFOC8gGRAGTlc",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {process.env.VERCEL_ENV === "production" ?? (
            <Script
              src="/stats/script.js"
              data-website-id="71441ea6-e810-4e9f-b10a-386892d7b509"
            />
          )}
          {children}
          <ReactQueryDevtools />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
